version: "3.7"

services:
  proxy:
    image: nginx:1.21.6
    build: ./proxy
    container_name: proxy-dbkp5
    ports:
      - 80:80
    restart: always  
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front-server
      - back-server
  front-server:
    image: frontend
    container_name: frontend
    build: ./front-end/frontkp5
    restart: always
    volumes:
      - ./front-end/frontkp5/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
    depends_on:
      - back-server
  back-server:
    image: backend
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: baslnwza007
      MYSQL_DATABASE: dbkp5
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./db/script:/docker-entrypoint-initdb.d/
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: baslnwza007
      MYSQL_DATABASE: dbkp5
