version: "3.3"

services:
  proxy:
    image: nginx:1.21.6
    container_name: proxy
    ports:
      - 80:80
    restart: always  
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front-server
      - back-server
  front-server:
    image: frontend
    container_name: frontend
    build: ./front-end/frontkp5
    restart: always
    volumes:
      - ./front-end/frontkp5/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
    depends_on:
      - back-server
  back-server:
    image: backend
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      SPRING_APPLICATION_JSON: '{
                  "spring.datasource.url"  : "jdbc:mysql://mysql:3306/dbkp5?allowPublicKeyRetrieval=true&useSSL=false",
                  "spring.datasource.username" : "root",
                  "spring.datasource.password" : "baslnwza007",
                  "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                  "spring.jpa.hibernate.ddl-auto" : "update"
            }'
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./db/script:/docker-entrypoint-initdb.d/
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: baslnwza007
      MYSQL_DATABASE: dbkp5
